{% set name = "genno" %}
{% set version = "1.27.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58a3074a31c6658a271068933d5628a5098a6f50cd77961a7819661185363eec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - dask >=2.14
    - graphviz
    - importlib_resources
    - python >=3.7
    - pandas >=1.0
    - pint
    - plotnine
    - PyYAML
    - sparse >=0.12
    - xarray >=0.17

test:
  imports:
    - genno
    - genno.compat.plotnine

about:
  home: https://github.com/khaeru/genno
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Efficient, transparent calculation on N-D data

extra:
  recipe-maintainers:
    - khaeru
    - glatterf42
