{% set name = "genno" %}
{% set version = "1.28.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ddc0de83a6279525feda8963dd84420d2930a5546786b18d4fdc16de019c8dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - dask >=2.14
    - graphviz
    - importlib_resources
    - python >={{ python_min }}
    - pandas >=1.0
    - pint
    - plotnine
    - PyYAML
    - sparse >=0.12
    - xarray >=0.17

test:
  requires:
    - python {{ python_min }}
  imports:
    - genno
    - genno.compat.plotnine

about:
  home: https://github.com/khaeru/genno
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Efficient, transparent calculation on N-D data

extra:
  recipe-maintainers:
    - khaeru
    - glatterf42
