{% set name = "genno" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e54e0777de6de7ca3e362996704710286db4e2d0376372b04269b203c58dae7b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - dask >=2.14
    - graphviz
    - python >=3.6
    - pandas >=1.0
    - pint
    - plotnine
    - PyYAML
    - setuptools
    - sparse >=0.12
    - xarray

test:
  imports:
    - genno
    - genno.compat.plotnine

about:
  home: https://github.com/khaeru/genno
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Efficient, transparent calculation on N-D data

extra:
  recipe-maintainers:
    - khaeru
