{% set name = "genno" %}
{% set version = "1.28.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 270504c790c4afc7116e613e412342376a30f540ba41ae2ead8ddfba22a7662d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - setuptools
    - versioningit
  run:
    - dask >=2.14
    - graphviz
    - importlib_resources
    - python >={{ python_min }}
    - pandas >=1.0
    - pint
    - plotnine
    - PyYAML
    - sparse >=0.12
    - xarray >=0.17

test:
  requires:
    - python {{ python_min }}
  imports:
    - genno
    - genno.compat.plotnine

about:
  home: https://github.com/khaeru/genno
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Efficient, transparent calculation on N-D data

extra:
  recipe-maintainers:
    - khaeru
    - glatterf42
